The preview of weg was not alligned well
eythaann/Seelen-UI pull request #195
Opened 2024-10-20 15:38 UTC by luriusTM

Only placement of the position has been calculated based on the configuration value.

2024-10-21 01:48 UTC, eythaann commented
@luriusTM thanks for you fix, this will be merged but first you need to sign the commit in order to be verified.
You can read more about this: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

2024-10-22 10:34 UTC, eythaann requested changes

2024-10-22 11:53 UTC, luriusTM commented on src/apps/seelenweg/modules/item/infra/UserApplication.tsx
> +    if (position == SeelenWegSide.Bottom) {
code technically you are right, although linter only allows me this way to commit a switch, so it is not look better. Inline switch is not available in js.

2024-10-22 12:35 UTC, eythaann commented on src/apps/seelenweg/modules/item/infra/UserApplication.tsx
> +    if (position == SeelenWegSide.Bottom) {
linter allows switch, only made it line by line instead all inline.

2024-10-22 12:40 UTC, eythaann requested changes

2024-10-22 12:40 UTC, eythaann commented on src/apps/seelenweg/modules/item/infra/UserApplication.tsx
> +      default: {
default should through an exception of type "Unimplemented".

2024-10-22 21:15 UTC, eythaann approved these changes

2024-10-22 21:17 UTC, merged