#154 Issue fix
eythaann/Seelen-UI pull request #273
Opened 2024-11-06 16:40 UTC by luriusTM

The issue here if you have passwordless wifi in the profile, then the deserialization fails with error. This fixes that and in case you would like to join to passwordless (public) wifi, then you need a bit different profile for that. This is added. Most of the case, public wifi authentication page  pop ups by default, but indication is not added.

2024-11-06 17:19 UTC, luriusTM commented
The "cargo fmt" command does the line ending change anyway...

2024-11-09 16:15 UTC, eythaann requested changes

2024-11-09 16:15 UTC, eythaann commented on src/background/modules/network/application/profile.template.empty.xml
rename the file to passwordless_profile.template.xml

2024-11-09 16:16 UTC, eythaann commented
only change the name of the file, and it's all

2024-11-09 18:46 UTC, eythaann approved these changes

2024-11-09 18:46 UTC, merged